### ISSUE TITLE
Running the game?

### ISSUE THREAD

**Issue by pbbpage** [kengz/Risk-game#1]
Hi, I'm trying to run the game, and I'm not sure how.  I believe I built the game using node as explained in your README doc, but so far no luck.  Any suggestions?

**Comment by kengz** [comment]
Just did a fresh download and run it, the instructions were okay.

What happened was I commented out the main methods in `main.js`. Look starting from line 40, 

```
// repeat(500, [0,0,1], './data/GS_0_0_1.json');
```

U just have to uncomment a line to run it.
This means run 500 games, for `<AI1_personality=0>, <AI2_personality=0>, <AI_1_goes_first>`, saving to the specified output `json`.
