### ISSUE TITLE
How to open the game shown in video?

### ISSUE THREAD

**Issue by ttuleyb** [kengz/Risk-game#5]
Hey, I've watched the video where you show off the AI agents playing against other types of AI agents. I successfully created files to analyse, however I don't know how to bring up the actual game and see the AI agents play against eachother like shown in the YouTube video.
Can you help?

**Comment by kengz** [comment]
Hi it's been a long time since I wrote this, but if I remember correctly it doesn't render the game itself; instead it just represents the game symbolically/functionally and runs it. Also curious what's the video you saw?

**Comment by ttuleyb** [comment]
Hello, sorry I've mistaken this project for what I've seen in that video. The actual github repo I was looking for was this one https://github.com/JohnR31415/Learning_AI_for_Board_Games

I was just looking around to see if the game of risk can be solved with an alphazero like AI agent (https://arxiv.org/abs/1712.01815) that just keeps playing against itself to master the game beyond what humans are capable of. 
Thanks for the reponse
